name: access-py-telemetry-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.13
  - jsonschema
  - pooch
  - pre-commit
  - ipython>=7.0.0,
  - pydantic>=2.0.0,
  - pyyaml>=6.0.0,
  - httpx>=0.28.0,
  - pytest
  - pip
  - coverage
  - mypy
  - ruff
  - pip:
    - codecov