"""Sphinx configuration for access-py-telemetry."""

import os
import sys

# Package is in src/ layout — ensure autodoc can import it
sys.path.insert(0, os.path.abspath("../src"))

import access_py_telemetry

# -- General configuration ---

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
]

myst_enable_extensions = ["colon_fence"]

templates_path = ["_templates"]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "access-py-telemetry"
copyright = "2024, ACCESS-NRI"
author = "ACCESS-NRI & Contributors"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = access_py_telemetry.__version__
# The full version, including alpha/beta/rc tags.
release = access_py_telemetry.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ---

# Placeholder theme — swap for your org theme when ready
html_theme = "sphinx_rtd_theme"
html_static_path: list[str] = []


intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "ipython": ("https://ipython.readthedocs.io/en/stable/", None),
}
